import { Editor } from './editor/editor.js';
import { AdvancedInteraction } from './editor/advanced-interaction.js';
import { AIStudio } from './ai/ai-ui.js';
import { saveProject, loadProject } from './project/storage.js';
import { exportCanvas } from './project/export.js';

const $=s=>document.querySelector(s), canvas=$('#editorCanvas');
const editor=new Editor(canvas,{onChange:render,onStatus:m=>$('#statusText').textContent=m});
new AdvancedInteraction(editor,canvas);
const ai=new AIStudio(editor,{modal:$('#modal'),title:$('#modalTitle'),body:$('#modalBody')});
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1800)};
function showCanvas(){ $('#emptyState').classList.add('hidden'); $('.canvas-wrap').style.display='block' }
function render(){renderLayers();renderInspector()}
function renderLayers(){const box=$('#layersList');if(!box)return;box.innerHTML='';editor.layers.slice().reverse().forEach(l=>{const row=document.createElement('div');row.className='layer'+(editor.selectedIds.includes(l.id)?' active':'');row.innerHTML=`<div class="thumb">${l.type==='text'?'T':l.type==='image'?'▧':l.type==='sticker'?(l.text||'☺'):'◇'}</div><div class="name">${l.name}</div><button data-a="hide">${l.hidden?'◌':'◉'}</button><button data-a="lock">${l.locked?'🔒':'↕'}</button><button data-a="dup">⧉</button>`;row.onclick=e=>{const a=e.target.closest('button')?.dataset.a;if(a==='hide')editor.toggleHidden(l.id);else if(a==='lock')editor.toggleLock(l.id);else if(a==='dup'){editor.select(l.id);editor.duplicateSelected()}else editor.select(l.id,e.shiftKey||e.metaKey||e.ctrlKey);render()};box.appendChild(row)})}
function field(label,id,value,type='text'){return `<div class="field"><label>${label}</label><input id="${id}" type="${type}" value="${value??''}"></div>`}
function renderInspector(){const o=editor.selected,body=$('#inspectorBody');if(!body)return;if(!o){body.innerHTML='<p class="muted">Select an object to edit it. Shift-click for multi-select.</p>';return}body.innerHTML=`${field('Name','pName',o.name)}<div class="grid2">${field('X','pX',Math.round(o.x),'number')}${field('Y','pY',Math.round(o.y),'number')}${field('Width','pW',Math.round(o.w||o.size||100),'number')}${field('Height','pH',Math.round(o.h||o.size||100),'number')}</div>${field('Opacity','pOpacity',o.opacity??1,'range')}${field('Rotation','pRotation',Math.round((o.rotation||0)*180/Math.PI),'range')}<div class="grid2"><button class="btn" id="rotL">↺ 90°</button><button class="btn" id="rotR">↻ 90°</button><button class="btn" id="flipX">Flip X</button><button class="btn" id="flipY">Flip Y</button></div>${o.type==='text'||o.type==='sticker'?`<div class="field"><label>Text</label><textarea id="pText">${o.text||''}</textarea></div><div class="grid2">${field('Size','pSize',o.size||72,'number')}${field('Weight','pWeight',o.weight||700,'number')}</div><div class="grid2">${field('Font','pFont',o.font||'Inter')}${field('Letter spacing','pSpacing',o.letterSpacing||0,'number')}</div>${o.type==='text'?'<div class="field"><label>Color</label><input id="pFill" type="color" value="'+(o.fill||'#111827')+'"></div>':''}`:''}${o.type==='image'?`<div class="grid2"><button class="btn" id="bright">Brightness</button><button class="btn" id="sat">Saturation</button></div>`:''}<div class="grid2"><button class="btn" id="duplicate">Duplicate</button><button class="btn" id="delete">Delete</button></div>`;
 const bind=(id,key,parse=v=>v)=>{const el=$('#'+id);if(!el)return;el.onchange=()=>editor.setProperty(key,parse(el.value))};bind('pName','name');bind('pX','x',Number);bind('pY','y',Number);bind('pW','w',v=>Math.max(10,Number(v)));bind('pH','h',v=>Math.max(10,Number(v)));bind('pOpacity','opacity',Number);bind('pRotation','rotation',v=>Number(v)*Math.PI/180);bind('pText','text');bind('pSize','size',Number);bind('pWeight','weight',Number);bind('pFont','font');bind('pSpacing','letterSpacing',Number);bind('pFill','fill');
 $('#rotL')?.addEventListener('click',()=>editor.rotate(-90));$('#rotR')?.addEventListener('click',()=>editor.rotate(90));$('#flipX')?.addEventListener('click',()=>editor.flip('x'));$('#flipY')?.addEventListener('click',()=>editor.flip('y'));$('#duplicate')?.addEventListener('click',()=>editor.duplicateSelected());$('#delete')?.addEventListener('click',()=>editor.deleteSelected());$('#bright')?.addEventListener('click',()=>editor.setProperty('brightness',Number(prompt('Brightness 0-200',o.brightness??100))));$('#sat')?.addEventListener('click',()=>editor.setProperty('saturation',Number(prompt('Saturation 0-200',o.saturation??100))));}
$('#uploadBtn').onclick=()=>$('#fileInput').click();$('#newBtn').onclick=()=>{editor.reset();$('#emptyState').classList.remove('hidden');$('.canvas-wrap').style.display='none';toast('New project')};$('#openBtn').onclick=()=>$('#fileInput').click();$('#saveBtn').onclick=()=>{const blob=saveProject(editor);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='jittoo-project.json';a.click();URL.revokeObjectURL(a.href);toast('Project saved')};$('#fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.type==='application/json'||f.name.endsWith('.json'))await loadProject(editor,f);else await editor.addImageFile(f);showCanvas();render();toast('Loaded')}catch(err){console.error(err);toast('Could not load file')}e.target.value=''};
$('#exportBtn').onclick=()=>{const format=prompt('Export format: png, jpg or webp','png')?.toLowerCase();if(['png','jpg','webp'].includes(format))exportCanvas(editor,format)};$('#undoBtn').onclick=()=>editor.undo();$('#redoBtn').onclick=()=>editor.redo();$('#zoomIn').onclick=()=>editor.zoomBy(1.1);$('#zoomOut').onclick=()=>editor.zoomBy(.9);$('#fitBtn').onclick=()=>editor.fit();$('#addLayerBtn').onclick=()=>editor.addShape();
$('.toolbar').addEventListener('click',e=>{const b=e.target.closest('.tool');if(!b)return;document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');b.dataset.tool==='ai'?ai.open():editor.activateTool(b.dataset.tool)});
['dragenter','dragover'].forEach(ev=>$('#stageViewport').addEventListener(ev,e=>{e.preventDefault();$('#stageViewport').classList.add('dragover')}));['dragleave','drop'].forEach(ev=>$('#stageViewport').addEventListener(ev,e=>{e.preventDefault();$('#stageViewport').classList.remove('dragover')}));$('#stageViewport').addEventListener('drop',async e=>{const f=e.dataTransfer.files[0];if(f?.type.startsWith('image/')){await editor.addImageFile(f);showCanvas();render()}});
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('#saveBtn').click()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?editor.redo():editor.undo()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='d'){e.preventDefault();editor.duplicateSelected()}if(e.key==='Delete'||e.key==='Backspace')editor.deleteSelected();if(e.key==='Escape'){editor.selectedIds=[];editor.selectedId=null;render()}});
render();