export class Editor{
 constructor(canvas,{onChange=()=>{},onStatus=()=>{}}={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.layers=[];this.selectedId=null;this.history=[];this.future=[];this.tool='select';this.zoom=1;this.onChange=onChange;this.onStatus=onStatus;this.drag=null;this.bind();this.render()}
 snapshot(){return JSON.stringify(this.layers)} push(){this.history.push(this.snapshot());if(this.history.length>60)this.history.shift();this.future=[];this.onChange()}
 restore(s){this.layers=JSON.parse(s);this.selectedId=this.layers.at(-1)?.id||null;this.render();this.onChange()}
 undo(){if(!this.history.length)return;this.future.push(this.snapshot());this.restore(this.history.pop())} redo(){if(!this.future.length)return;this.history.push(this.snapshot());this.restore(this.future.pop())}
 reset(){this.layers=[];this.selectedId=null;this.history=[];this.future=[];this.render();this.onChange()}
 add(layer){this.push();layer.id=crypto.randomUUID();layer.x??=this.canvas.width/2;layer.y??=this.canvas.height/2;layer.rotation??=0;layer.opacity??=1;layer.scaleX??=1;layer.scaleY??=1;layer.locked??=false;this.layers.push(layer);this.selectedId=layer.id;this.render()}
 addShape(){this.add({type:'shape',name:'Rectangle',x:540,y:540,w:260,h:180,fill:'#7357ff',radius:18})}
 async addImageFile(file){const url=URL.createObjectURL(file);const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});this.add({type:'image',name:file.name||'Photo',img:img.src,w:Math.min(700,img.width),h:Math.min(700,img.height),naturalW:img.width,naturalH:img.height});URL.revokeObjectURL(url)}
 addText(text='JITTOO'){this.add({type:'text',name:'Text',text,x:540,y:540,size:72,font:'Inter',weight:700,fill:'#111827',align:'center',stroke:null,shadow:null})}
 addSticker(char='✨'){this.add({type:'sticker',name:'Sticker',text:char,x:540,y:540,size:120,align:'center'})}
 select(id){this.selectedId=id;this.render()} activateTool(t){this.tool=t;if(t==='text')this.addText();if(t==='sticker')this.addSticker();if(t==='shape')this.addShape();if(t==='image')document.querySelector('#fileInput')?.click();this.onStatus(t==='select'?'Ready':`${t} tool`)}
 get selected(){return this.layers.find(x=>x.id===this.selectedId)}
 moveLayer(id,dir){const i=this.layers.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=this.layers.length)return;this.push();[this.layers[i],this.layers[j]]=[this.layers[j],this.layers[i]];this.render()}
 toggleLock(id){const l=this.layers.find(x=>x.id===id);if(!l)return;this.push();l.locked=!l.locked;this.render()}
 deleteSelected(){if(!this.selectedId)return;this.push();this.layers=this.layers.filter(x=>x.id!==this.selectedId);this.selectedId=null;this.render()}
 zoomBy(n){this.zoom=Math.max(.25,Math.min(3,this.zoom*n));this.canvas.style.transform=`scale(${this.zoom})`;document.querySelector('#zoomValue').textContent=Math.round(this.zoom*100)+'%'} fit(){this.zoom=1;this.canvas.style.transform='scale(1)';document.querySelector('#zoomValue').textContent='100%'}
 hit(x,y){for(let i=this.layers.length-1;i>=0;i--){const l=this.layers[i];if(l.hidden||l.locked)continue;const w=l.w||l.size||100,h=l.h||l.size||100;if(Math.abs(x-l.x)<=w/2&&Math.abs(y-l.y)<=h/2)return l}return null}
 point(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*this.canvas.width/r.width,y:(e.clientY-r.top)*this.canvas.height/r.height}}
 bind(){this.canvas.addEventListener('pointerdown',e=>{const p=this.point(e),l=this.hit(p.x,p.y);if(this.tool==='select'&&l){this.select(l.id);this.push();this.drag={x:p.x,y:p.y,ox:l.x,oy:l.y};this.canvas.setPointerCapture(e.pointerId)}});this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const p=this.point(e),l=this.selected;if(l&&!l.locked){l.x=this.drag.ox+(p.x-this.drag.x);l.y=this.drag.oy+(p.y-this.drag.y);this.render()}});this.canvas.addEventListener('pointerup',()=>{this.drag=null;this.onChange()});this.canvas.addEventListener('dblclick',()=>this.selected?.type==='text'&&(this.selected.text=prompt('Text',this.selected.text)||this.selected.text,this.render()))}
 render(){const c=this.ctx;c.clearRect(0,0,this.canvas.width,this.canvas.height);c.fillStyle='#fff';c.fillRect(0,0,this.canvas.width,this.canvas.height);for(const l of this.layers)if(!l.hidden)this.draw(l);this.onChange()}
 draw(l){const c=this.ctx;c.save();c.globalAlpha=l.opacity??1;c.translate(l.x,l.y);c.rotate(l.rotation||0);if(l.type==='image'){const im=new Image();im.src=l.img;if(im.complete)c.drawImage(im,-l.w/2,-l.h/2,l.w,l.h);else im.onload=()=>this.render()}else if(l.type==='text'||l.type==='sticker'){c.textAlign=l.align||'center';c.textBaseline='middle';c.font=`${l.weight||700} ${l.size||64}px ${l.font||'sans-serif'}`;if(l.shadow){c.shadowColor=l.shadow.color;c.shadowBlur=l.shadow.blur||12;c.shadowOffsetX=l.shadow.x||0;c.shadowOffsetY=l.shadow.y||4}c.fillStyle=l.fill||'#111';c.fillText(l.text||'',0,0)}else{c.fillStyle=l.fill||'#7357ff';const w=l.w||200,h=l.h||120,r=Math.min(l.radius||0,w/2,h/2);c.beginPath();c.roundRect(-w/2,-h/2,w,h,r);c.fill()}c.restore()}
}