export class Editor {
  constructor(canvas,{onChange=()=>{},onStatus=()=>{}}={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.layers=[];this.selectedId=null;this.selectedIds=[];this.history=[];this.future=[];this.tool='select';this.zoom=1;this.onChange=onChange;this.onStatus=onStatus;this.drag=null;this.transform=null;this.snap=10;this.bind();this.render()}
  snapshot(){return JSON.stringify(this.layers)}
  push(){this.history.push(this.snapshot());if(this.history.length>80)this.history.shift();this.future=[]}
  restore(s){this.layers=JSON.parse(s);this.selectedId=this.layers.at(-1)?.id||null;this.selectedIds=this.selectedId?[this.selectedId]:[];this.render()}
  undo(){if(!this.history.length)return;this.future.push(this.snapshot());this.restore(this.history.pop());this.onChange()}
  redo(){if(!this.future.length)return;this.history.push(this.snapshot());this.restore(this.future.pop());this.onChange()}
  reset(){this.layers=[];this.selectedId=null;this.selectedIds=[];this.history=[];this.future=[];this.render();this.onChange()}
  add(layer){this.push();layer.id=crypto.randomUUID();layer.x??=this.canvas.width/2;layer.y??=this.canvas.height/2;layer.rotation??=0;layer.opacity??=1;layer.scaleX??=1;layer.scaleY??=1;layer.locked??=false;layer.hidden??=false;this.layers.push(layer);this.select(layer.id);this.render()}
  addShape(){this.add({type:'shape',name:'Rectangle',x:540,y:540,w:260,h:180,fill:'#7357ff',radius:18,gradient:null})}
  async addImageFile(file){const url=URL.createObjectURL(file),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});this.add({type:'image',name:file.name||'Photo',img:img.src,w:Math.min(700,img.width),h:Math.min(700,img.height),naturalW:img.width,naturalH:img.height,brightness:100,contrast:100,saturation:100,grayscale:0,blur:0,flipX:false,flipY:false,crop:null});URL.revokeObjectURL(url)}
  addText(text='JITTOO'){this.add({type:'text',name:'Text',text,x:540,y:540,size:72,font:'Inter',weight:700,fill:'#111827',align:'center',letterSpacing:0,lineHeight:1.2,stroke:null,shadow:null,glow:null})}
  addSticker(char='✨'){this.add({type:'sticker',name:'Sticker',text:char,x:540,y:540,size:120,align:'center'})}
  select(id,add=false){if(add){if(!this.selectedIds.includes(id))this.selectedIds.push(id)}else this.selectedIds=[id];this.selectedId=id;this.render();this.onChange()}
  get selected(){return this.layers.find(x=>x.id===this.selectedId)}
  get selection(){return this.layers.filter(x=>this.selectedIds.includes(x.id))}
  activateTool(t){this.tool=t;if(t==='text')this.addText();if(t==='sticker')this.addSticker();if(t==='shape')this.addShape();if(t==='image')document.querySelector('#fileInput')?.click();this.onStatus(t==='select'?'Ready':`${t} tool`)}
  moveLayer(id,dir){const i=this.layers.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=this.layers.length)return;this.push();[this.layers[i],this.layers[j]]=[this.layers[j],this.layers[i]];this.render()}
  duplicateSelected(){const src=this.selection;if(!src.length)return;this.push();const copies=src.map(l=>({...structuredClone(l),id:crypto.randomUUID(),name:`${l.name} copy`,x:l.x+20,y:l.y+20,locked:false}));this.layers.push(...copies);this.selectedIds=copies.map(x=>x.id);this.selectedId=copies.at(-1).id;this.render()}
  toggleLock(id){const l=this.layers.find(x=>x.id===id);if(!l)return;this.push();l.locked=!l.locked;this.render()}
  toggleHidden(id){const l=this.layers.find(x=>x.id===id);if(!l)return;this.push();l.hidden=!l.hidden;this.render()}
  deleteSelected(){if(!this.selectedIds.length)return;this.push();this.layers=this.layers.filter(x=>!this.selectedIds.includes(x.id));this.selectedIds=[];this.selectedId=null;this.render()}
  setProperty(key,value){if(!this.selection.length)return;this.push();this.selection.forEach(l=>l[key]=value);this.render()}
  rotate(deg){if(!this.selection.length)return;this.push();this.selection.forEach(l=>l.rotation=(l.rotation||0)+deg*Math.PI/180);this.render()}
  flip(axis){if(!this.selection.length)return;this.push();this.selection.forEach(l=>axis==='x'?l.flipX=!l.flipX:l.flipY=!l.flipY);this.render()}
  zoomBy(n){this.zoom=Math.max(.25,Math.min(3,this.zoom*n));this.canvas.style.transform=`scale(${this.zoom})`;document.querySelector('#zoomValue').textContent=Math.round(this.zoom*100)+'%'}
  fit(){this.zoom=1;this.canvas.style.transform='scale(1)';document.querySelector('#zoomValue').textContent='100%'}
  bounds(l){const w=(l.w||l.size||100)*Math.abs(l.scaleX||1),h=(l.h||l.size||100)*Math.abs(l.scaleY||1);return{x:l.x-w/2,y:l.y-h/2,w,h}}
  hit(x,y){for(let i=this.layers.length-1;i>=0;i--){const l=this.layers[i];if(l.hidden||l.locked)continue;const b=this.bounds(l);if(x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h)return l}return null}
  point(e){const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*this.canvas.width/r.width,y:(e.clientY-r.top)*this.canvas.height/r.height}}
  snapPoint(x,y,l){const others=this.layers.filter(o=>o.id!==l.id&&!o.hidden);for(const o of others){const b=this.bounds(o);const ox=[b.x,b.x+b.w/2,b.x+b.w],oy=[b.y,b.y+b.h/2,b.y+b.h];const w=(l.w||l.size||100),h=(l.h||l.size||100);const lx=[x-w/2,x,x+w/2],ly=[y-h/2,y,y+h/2];for(let i=0;i<lx.length;i++)for(let j=0;j<ox.length;j++)if(Math.abs(lx[i]-ox[j])<this.snap)x+=ox[j]-lx[i];for(let i=0;i<ly.length;i++)for(let j=0;j<oy.length;j++)if(Math.abs(ly[i]-oy[j])<this.snap)y+=oy[j]-ly[i]}return{x,y}}
  bind(){
    this.canvas.addEventListener('pointerdown',e=>{const p=this.point(e);if(this.tool!=='select')return;const l=this.hit(p.x,p.y);if(!l){this.selectedIds=[];this.selectedId=null;this.render();return}this.select(l.id,e.shiftKey||e.metaKey||e.ctrlKey);this.push();this.drag={x:p.x,y:p.y,items:this.selection.map(x=>({id:x.id,x:x.x,y:x.y}))};this.canvas.setPointerCapture(e.pointerId)});
    this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const p=this.point(e),dx=p.x-this.drag.x,dy=p.y-this.drag.y;this.drag.items.forEach(s=>{const l=this.layers.find(x=>x.id===s.id);if(l&&!l.locked){let nx=s.x+dx,ny=s.y+dy;if(this.selection.length===1){const q=this.snapPoint(nx,ny,l);nx=q.x;ny=q.y}l.x=nx;l.y=ny}});this.render()});
    this.canvas.addEventListener('pointerup',()=>{if(this.drag)this.onStatus('Moved');this.drag=null;this.onChange()});
    this.canvas.addEventListener('dblclick',()=>this.selected?.type==='text'&&(this.selected.text=prompt('Text',this.selected.text)||this.selected.text,this.render()));
  }
  render(){const c=this.ctx;c.clearRect(0,0,this.canvas.width,this.canvas.height);c.fillStyle='#fff';c.fillRect(0,0,this.canvas.width,this.canvas.height);for(const l of this.layers)if(!l.hidden)this.draw(l);this.drawSelection();this.onChange()}
  drawSelection(){const c=this.ctx;c.save();c.strokeStyle='#7c3aed';c.lineWidth=2/this.zoom;c.setLineDash([7/this.zoom,5/this.zoom]);this.selection.forEach(l=>{const b=this.bounds(l);c.strokeRect(b.x,b.y,b.w,b.h)});c.restore()}
  draw(l){const c=this.ctx;c.save();c.globalAlpha=l.opacity??1;c.translate(l.x,l.y);c.rotate(l.rotation||0);c.scale((l.flipX?-1:1)*(l.scaleX||1),(l.flipY?-1:1)*(l.scaleY||1));if(l.type==='image'){const im=new Image();im.src=l.img;if(im.complete){c.filter=`brightness(${l.brightness??100}%) contrast(${l.contrast??100}%) saturate(${l.saturation??100}%) grayscale(${l.grayscale??0}%) blur(${l.blur??0}px)`;c.drawImage(im,-l.w/2,-l.h/2,l.w,l.h)}else im.onload=()=>this.render()}else if(l.type==='text'||l.type==='sticker'){c.textAlign=l.align||'center';c.textBaseline='middle';c.font=`${l.weight||700} ${l.size||64}px ${l.font||'sans-serif'}`;if(l.shadow){c.shadowColor=l.shadow.color;c.shadowBlur=l.shadow.blur||12;c.shadowOffsetX=l.shadow.x||0;c.shadowOffsetY=l.shadow.y||4}if(l.stroke){c.strokeStyle=l.stroke.color;c.lineWidth=l.stroke.width||2;c.strokeText(l.text||'',0,0)}c.fillStyle=l.fill||'#111';c.fillText(l.text||'',0,0)}else{c.fillStyle=l.fill||'#7357ff';const w=l.w||200,h=l.h||120,r=Math.min(l.radius||0,w/2,h/2);c.beginPath();c.roundRect(-w/2,-h/2,w,h,r);if(l.gradient){const g=c.createLinearGradient(-w/2,0,w/2,0);g.addColorStop(0,l.gradient[0]);g.addColorStop(1,l.gradient[1]);c.fillStyle=g}c.fill()}c.restore()}
}